// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

/**
 * AuthData
 */
export type AuthData = {
    /**
     * User Id
     */
    user_id: number;
    /**
     * Username
     */
    username: string;
};

/**
 * SigninResponse
 */
export type SigninResponse = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Message
     */
    message: string;
    data?: AuthData | null;
};

/**
 * LoginFormSchema
 */
export type LoginFormSchema = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * SignoutResponse
 */
export type SignoutResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Message
     */
    message?: string | null;
    /**
     * Data
     */
    data?: null;
};

/**
 * WhoamiResponse
 */
export type WhoamiResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Message
     */
    message?: string | null;
    data: AuthData;
};

/**
 * GetWarehousesResponse
 */
export type GetWarehousesResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Message
     */
    message?: string | null;
    /**
     * Data
     */
    data: Array<WarehouseSchema>;
};

/**
 * WarehouseLocationSchema
 */
export type WarehouseLocationSchema = {
    /**
     * Created
     */
    created: string;
    /**
     * Changed
     */
    changed: string;
    /**
     * Code
     */
    code: string;
};

/**
 * WarehouseSchema
 */
export type WarehouseSchema = {
    /**
     * Created
     */
    created: string;
    /**
     * Changed
     */
    changed: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Locations
     */
    locations: Array<WarehouseLocationSchema>;
};

/**
 * GetWarehouseLocationResponse
 */
export type GetWarehouseLocationResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Message
     */
    message?: string | null;
    data: WarehouseLocationDetailSchema;
};

/**
 * PackageSchema
 */
export type PackageSchema = {
    /**
     * Created
     */
    created: string;
    /**
     * Changed
     */
    changed: string;
    /**
     * Type
     */
    type: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Amount
     */
    amount: number;
    /**
     * Unit
     */
    unit: string;
};

/**
 * StockItemSchema
 */
export type StockItemSchema = {
    /**
     * Created
     */
    created: string;
    /**
     * Changed
     */
    changed: string;
    /**
     * Name
     */
    name: string;
    /**
     * Code
     */
    code: string;
};

/**
 * WarehouseItemSchema
 * Atomic unit of the inventory - uniquely identifiable and trackable item in a warehouse
 */
export type WarehouseItemSchema = {
    /**
     * Created
     */
    created: string;
    /**
     * Changed
     */
    changed: string;
    /**
     * Code
     */
    code: string;
    stock_item: StockItemSchema;
    /**
     * Unit Of Measure
     */
    unit_of_measure: string;
    /**
     * Amount
     */
    amount: number;
    package: PackageSchema | null;
};

/**
 * WarehouseLocationDetailSchema
 */
export type WarehouseLocationDetailSchema = {
    /**
     * Created
     */
    created: string;
    /**
     * Changed
     */
    changed: string;
    /**
     * Code
     */
    code: string;
    /**
     * Items
     */
    items: Array<WarehouseItemSchema>;
};

/**
 * Input
 */
export type Input = {
    /**
     * Page
     */
    page?: number;
    /**
     * Page Size
     */
    page_size?: number;
};

/**
 * PagedProductSchema
 */
export type PagedProductSchema = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Message
     */
    message?: string | null;
    /**
     * Data
     */
    data: Array<ProductSchema>;
    /**
     * Count
     */
    count: number;
    /**
     * Next
     */
    next: number | null;
    /**
     * Previous
     */
    previous: number | null;
};

/**
 * ProductSchema
 */
export type ProductSchema = {
    /**
     * Created
     */
    created: string;
    /**
     * Changed
     */
    changed: string;
    /**
     * Name
     */
    name: string;
    /**
     * Code
     */
    code: string;
    /**
     * Type
     */
    type: string;
    /**
     * Unit
     */
    unit: string;
    /**
     * Group
     */
    group?: string | null;
    /**
     * Unit Weight
     */
    unit_weight: number;
    /**
     * Base Price
     */
    base_price: number;
    /**
     * Purchase Price
     */
    purchase_price: number;
    /**
     * Currency
     */
    currency: string;
    /**
     * Attributes
     */
    attributes?: {
        [key: string]: string;
    };
};

/**
 * GetProductResponse
 */
export type GetProductResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Message
     */
    message?: string | null;
    data: ProductSchema;
};

/**
 * GetProductWarehouseInfoResponse
 */
export type GetProductWarehouseInfoResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Message
     */
    message?: string | null;
    /**
     * Data
     */
    data: Array<WarehouseExpandedSchema>;
};

/**
 * WarehouseExpandedSchema
 */
export type WarehouseExpandedSchema = {
    /**
     * Created
     */
    created: string;
    /**
     * Changed
     */
    changed: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Locations
     */
    locations: Array<WarehouseLocationDetailSchema>;
};

/**
 * GetProductWarehouseAvailabilityResponse
 */
export type GetProductWarehouseAvailabilityResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Message
     */
    message?: string | null;
    data: ProductWarehouseAvailability;
};

/**
 * ProductWarehouseAvailability
 * Summary of item's availability in the warehouse
 */
export type ProductWarehouseAvailability = {
    /**
     * Total Amount
     */
    total_amount: number;
    /**
     * Available Amount
     */
    available_amount: number;
};

/**
 * ContactPersonSchema
 * Schema for ContactPerson output
 */
export type ContactPersonSchema = {
    /**
     * Created
     */
    created: string;
    /**
     * Changed
     */
    changed: string;
    /**
     * Title Pre
     */
    title_pre?: string | null;
    /**
     * First Name
     */
    first_name: string;
    /**
     * Middle Name
     */
    middle_name?: string | null;
    /**
     * Last Name
     */
    last_name: string;
    /**
     * Title Post
     */
    title_post?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Birth Date
     */
    birth_date?: string | null;
    /**
     * Street
     */
    street?: string | null;
    /**
     * City
     */
    city?: string | null;
    /**
     * Postal Code
     */
    postal_code?: string | null;
    /**
     * State
     */
    state?: string | null;
    /**
     * Profile Picture Url
     */
    profile_picture_url?: string | null;
    /**
     * Is Deleted
     */
    is_deleted: boolean;
    /**
     * Note
     */
    note?: string | null;
};

/**
 * CustomerGroupSchema
 * Schema for CustomerGroup output
 */
export type CustomerGroupSchema = {
    /**
     * Created
     */
    created: string;
    /**
     * Changed
     */
    changed: string;
    /**
     * Code
     */
    code: string;
    /**
     * Name
     */
    name: string;
};

/**
 * CustomerSchema
 * Schema for Customer output
 */
export type CustomerSchema = {
    /**
     * Created
     */
    created: string;
    /**
     * Changed
     */
    changed: string;
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Code
     */
    code: string;
    /**
     * Street
     */
    street?: string | null;
    /**
     * City
     */
    city?: string | null;
    /**
     * Postal Code
     */
    postal_code?: string | null;
    /**
     * State
     */
    state: string;
    /**
     * Tax Identification
     */
    tax_identification?: string | null;
    /**
     * Identification
     */
    identification?: string | null;
    /**
     * Customer Type
     */
    customer_type: string;
    /**
     * Price Type
     */
    price_type: string;
    /**
     * Invoice Due Days
     */
    invoice_due_days: number;
    /**
     * Block After Due Days
     */
    block_after_due_days: number;
    /**
     * Data Collection Agreement
     */
    data_collection_agreement: boolean;
    /**
     * Marketing Data Use Agreement
     */
    marketing_data_use_agreement: boolean;
    /**
     * Is Valid
     */
    is_valid: boolean;
    /**
     * Is Deleted
     */
    is_deleted: boolean;
    /**
     * Owner
     */
    owner?: string | null;
    /**
     * Responsible User
     */
    responsible_user?: string | null;
    group: CustomerGroupSchema;
    /**
     * Contacts
     */
    contacts?: Array<ContactPersonSchema>;
    /**
     * Note
     */
    note?: string | null;
    /**
     * Register Information
     */
    register_information?: string | null;
};

/**
 * PagedCustomerSchema
 */
export type PagedCustomerSchema = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Message
     */
    message?: string | null;
    /**
     * Data
     */
    data: Array<CustomerSchema>;
    /**
     * Count
     */
    count: number;
    /**
     * Next
     */
    next: number | null;
    /**
     * Previous
     */
    previous: number | null;
};

/**
 * BaseResponse
 */
export type BaseResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Message
     */
    message?: string | null;
    /**
     * Data
     */
    data: unknown;
};

/**
 * GetCustomerResponse
 */
export type GetCustomerResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Message
     */
    message?: string | null;
    data: CustomerSchema;
};

/**
 * InboundOrderItemSchema
 */
export type InboundOrderItemSchema = {
    /**
     * Created
     */
    created: string;
    /**
     * Changed
     */
    changed: string;
    product: ProductSchema;
    /**
     * Amount
     */
    amount: number;
    /**
     * Unit Price
     */
    unit_price: number;
};

/**
 * InboundOrderSchema
 */
export type InboundOrderSchema = {
    /**
     * Created
     */
    created: string;
    /**
     * Changed
     */
    changed: string;
    /**
     * Code
     */
    code: string;
    /**
     * External Code
     */
    external_code?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Note
     */
    note?: string | null;
    supplier: CustomerSchema;
    /**
     * Items
     */
    items?: Array<InboundOrderItemSchema>;
    /**
     * Currency
     */
    currency: string;
    /**
     * Warehouse Order Code
     */
    warehouse_order_code: string | null;
    state: InboundOrderState;
};

/**
 * InboundOrderState
 */
export type InboundOrderState = 'draft' | 'submitted' | 'putaway' | 'completed' | 'cancelled';

/**
 * PagedInboundOrderSchema
 */
export type PagedInboundOrderSchema = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Message
     */
    message?: string | null;
    /**
     * Data
     */
    data: Array<InboundOrderSchema>;
    /**
     * Count
     */
    count: number;
    /**
     * Next
     */
    next: number | null;
    /**
     * Previous
     */
    previous: number | null;
};

/**
 * GetInboundOrderResponse
 */
export type GetInboundOrderResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Message
     */
    message?: string | null;
    data: InboundOrderSchema;
};

/**
 * InboundOrderCreateOrUpdateSchema
 */
export type InboundOrderCreateOrUpdateSchema = {
    /**
     * External Code
     */
    external_code?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Note
     */
    note?: string | null;
    /**
     * Currency
     */
    currency: string;
    /**
     * Supplier Code
     */
    supplier_code: string;
    /**
     * Supplier Name
     */
    supplier_name: string;
    state?: InboundOrderState | null;
};

/**
 * CreateInboundOrderItemResponse
 */
export type CreateInboundOrderItemResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Message
     */
    message?: string | null;
    data: InboundOrderItemSchema;
};

/**
 * InboundOrderItemCreateSchema
 */
export type InboundOrderItemCreateSchema = {
    /**
     * Product Code
     */
    product_code: string;
    /**
     * Product Name
     */
    product_name: string;
    /**
     * Amount
     */
    amount: number;
    /**
     * Unit Price
     */
    unit_price: number;
};

/**
 * InboundOrderTransitionSchema
 */
export type InboundOrderTransitionSchema = {
    state: InboundOrderState;
};

/**
 * EmptyResponse
 */
export type EmptyResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Message
     */
    message?: string | null;
    /**
     * Data
     */
    data?: null;
};

export type WarehouseApiRoutesAuthLoginUserData = {
    body: LoginFormSchema;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type WarehouseApiRoutesAuthLoginUserErrors = {
    /**
     * Unauthorized
     */
    401: SigninResponse;
};

export type WarehouseApiRoutesAuthLoginUserError = WarehouseApiRoutesAuthLoginUserErrors[keyof WarehouseApiRoutesAuthLoginUserErrors];

export type WarehouseApiRoutesAuthLoginUserResponses = {
    /**
     * OK
     */
    200: SigninResponse;
};

export type WarehouseApiRoutesAuthLoginUserResponse = WarehouseApiRoutesAuthLoginUserResponses[keyof WarehouseApiRoutesAuthLoginUserResponses];

export type WarehouseApiRoutesAuthLogoutUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type WarehouseApiRoutesAuthLogoutUserResponses = {
    /**
     * OK
     */
    200: SignoutResponse;
};

export type WarehouseApiRoutesAuthLogoutUserResponse = WarehouseApiRoutesAuthLogoutUserResponses[keyof WarehouseApiRoutesAuthLogoutUserResponses];

export type WarehouseApiRoutesAuthWhoamiData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/whoami';
};

export type WarehouseApiRoutesAuthWhoamiErrors = {
    /**
     * Unauthorized
     */
    401: SigninResponse;
};

export type WarehouseApiRoutesAuthWhoamiError = WarehouseApiRoutesAuthWhoamiErrors[keyof WarehouseApiRoutesAuthWhoamiErrors];

export type WarehouseApiRoutesAuthWhoamiResponses = {
    /**
     * OK
     */
    200: WhoamiResponse;
};

export type WarehouseApiRoutesAuthWhoamiResponse = WarehouseApiRoutesAuthWhoamiResponses[keyof WarehouseApiRoutesAuthWhoamiResponses];

export type WarehouseApiRoutesWarehouseGetWarehousesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/warehouses';
};

export type WarehouseApiRoutesWarehouseGetWarehousesResponses = {
    /**
     * OK
     */
    200: GetWarehousesResponse;
};

export type WarehouseApiRoutesWarehouseGetWarehousesResponse = WarehouseApiRoutesWarehouseGetWarehousesResponses[keyof WarehouseApiRoutesWarehouseGetWarehousesResponses];

export type WarehouseApiRoutesWarehouseGetWarehouseLocationData = {
    body?: never;
    path: {
        /**
         * Warehouse Location Code
         */
        warehouse_location_code: string;
    };
    query?: never;
    url: '/api/v1/locations/{warehouse_location_code}';
};

export type WarehouseApiRoutesWarehouseGetWarehouseLocationResponses = {
    /**
     * OK
     */
    200: GetWarehouseLocationResponse;
};

export type WarehouseApiRoutesWarehouseGetWarehouseLocationResponse = WarehouseApiRoutesWarehouseGetWarehouseLocationResponses[keyof WarehouseApiRoutesWarehouseGetWarehouseLocationResponses];

export type WarehouseApiRoutesWarehouseGetWarehouseOrderData = {
    body?: never;
    path: {
        /**
         * Code
         */
        code: string;
    };
    query?: never;
    url: '/api/v1/orders-incoming/{code}';
};

export type WarehouseApiRoutesWarehouseGetWarehouseOrderResponses = {
    /**
     * OK
     */
    200: GetWarehouseLocationResponse;
};

export type WarehouseApiRoutesWarehouseGetWarehouseOrderResponse = WarehouseApiRoutesWarehouseGetWarehouseOrderResponses[keyof WarehouseApiRoutesWarehouseGetWarehouseOrderResponses];

export type WarehouseApiRoutesProductGetProductsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Search Term
         */
        search_term?: string | null;
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/v1/products';
};

export type WarehouseApiRoutesProductGetProductsResponses = {
    /**
     * OK
     */
    200: PagedProductSchema;
};

export type WarehouseApiRoutesProductGetProductsResponse = WarehouseApiRoutesProductGetProductsResponses[keyof WarehouseApiRoutesProductGetProductsResponses];

export type WarehouseApiRoutesProductGetProductData = {
    body?: never;
    path: {
        /**
         * Product Code
         */
        product_code: string;
    };
    query?: never;
    url: '/api/v1/products/{product_code}';
};

export type WarehouseApiRoutesProductGetProductResponses = {
    /**
     * OK
     */
    200: GetProductResponse;
};

export type WarehouseApiRoutesProductGetProductResponse = WarehouseApiRoutesProductGetProductResponses[keyof WarehouseApiRoutesProductGetProductResponses];

export type WarehouseApiRoutesProductGetProductWarehouseInfoData = {
    body?: never;
    path: {
        /**
         * Product Code
         */
        product_code: string;
    };
    query?: never;
    url: '/api/v1/products/{product_code}/warehouse-info';
};

export type WarehouseApiRoutesProductGetProductWarehouseInfoResponses = {
    /**
     * OK
     */
    200: GetProductWarehouseInfoResponse;
};

export type WarehouseApiRoutesProductGetProductWarehouseInfoResponse = WarehouseApiRoutesProductGetProductWarehouseInfoResponses[keyof WarehouseApiRoutesProductGetProductWarehouseInfoResponses];

export type WarehouseApiRoutesProductGetProductWarehouseAvailabilityData = {
    body?: never;
    path: {
        /**
         * Product Code
         */
        product_code: string;
    };
    query?: never;
    url: '/api/v1/products/{product_code}/warehouse-availablity';
};

export type WarehouseApiRoutesProductGetProductWarehouseAvailabilityResponses = {
    /**
     * OK
     */
    200: GetProductWarehouseAvailabilityResponse;
};

export type WarehouseApiRoutesProductGetProductWarehouseAvailabilityResponse = WarehouseApiRoutesProductGetProductWarehouseAvailabilityResponses[keyof WarehouseApiRoutesProductGetProductWarehouseAvailabilityResponses];

export type WarehouseApiRoutesCustomerGetCustomersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Search Term
         */
        search_term?: string | null;
        /**
         * Is Deleted
         */
        is_deleted?: boolean;
        /**
         * Is Active
         */
        is_active?: boolean;
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/v1/customers';
};

export type WarehouseApiRoutesCustomerGetCustomersErrors = {
    /**
     * Not Found
     */
    404: BaseResponse;
};

export type WarehouseApiRoutesCustomerGetCustomersError = WarehouseApiRoutesCustomerGetCustomersErrors[keyof WarehouseApiRoutesCustomerGetCustomersErrors];

export type WarehouseApiRoutesCustomerGetCustomersResponses = {
    /**
     * OK
     */
    200: PagedCustomerSchema;
};

export type WarehouseApiRoutesCustomerGetCustomersResponse = WarehouseApiRoutesCustomerGetCustomersResponses[keyof WarehouseApiRoutesCustomerGetCustomersResponses];

export type WarehouseApiRoutesCustomerGetCustomerData = {
    body?: never;
    path: {
        /**
         * Customer Code
         */
        customer_code: string;
    };
    query?: never;
    url: '/api/v1/customers/{customer_code}';
};

export type WarehouseApiRoutesCustomerGetCustomerResponses = {
    /**
     * OK
     */
    200: GetCustomerResponse;
};

export type WarehouseApiRoutesCustomerGetCustomerResponse = WarehouseApiRoutesCustomerGetCustomerResponses[keyof WarehouseApiRoutesCustomerGetCustomerResponses];

export type WarehouseApiRoutesOrdersGetInboundOrdersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Search Term
         */
        search_term?: string | null;
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/v1/orders';
};

export type WarehouseApiRoutesOrdersGetInboundOrdersResponses = {
    /**
     * OK
     */
    200: PagedInboundOrderSchema;
};

export type WarehouseApiRoutesOrdersGetInboundOrdersResponse = WarehouseApiRoutesOrdersGetInboundOrdersResponses[keyof WarehouseApiRoutesOrdersGetInboundOrdersResponses];

export type WarehouseApiRoutesOrdersCreateInboundOrderData = {
    body: InboundOrderCreateOrUpdateSchema;
    path?: never;
    query?: never;
    url: '/api/v1/orders';
};

export type WarehouseApiRoutesOrdersCreateInboundOrderResponses = {
    /**
     * OK
     */
    200: GetInboundOrderResponse;
};

export type WarehouseApiRoutesOrdersCreateInboundOrderResponse = WarehouseApiRoutesOrdersCreateInboundOrderResponses[keyof WarehouseApiRoutesOrdersCreateInboundOrderResponses];

export type WarehouseApiRoutesOrdersGetInboundOrderData = {
    body?: never;
    path: {
        /**
         * Order Code
         */
        order_code: string;
    };
    query?: never;
    url: '/api/v1/orders/{order_code}';
};

export type WarehouseApiRoutesOrdersGetInboundOrderResponses = {
    /**
     * OK
     */
    200: GetInboundOrderResponse;
};

export type WarehouseApiRoutesOrdersGetInboundOrderResponse = WarehouseApiRoutesOrdersGetInboundOrderResponses[keyof WarehouseApiRoutesOrdersGetInboundOrderResponses];

export type WarehouseApiRoutesOrdersUpdateInboundOrderData = {
    body: InboundOrderCreateOrUpdateSchema;
    path: {
        /**
         * Order Code
         */
        order_code: string;
    };
    query?: never;
    url: '/api/v1/orders/{order_code}';
};

export type WarehouseApiRoutesOrdersUpdateInboundOrderResponses = {
    /**
     * OK
     */
    200: GetInboundOrderResponse;
};

export type WarehouseApiRoutesOrdersUpdateInboundOrderResponse = WarehouseApiRoutesOrdersUpdateInboundOrderResponses[keyof WarehouseApiRoutesOrdersUpdateInboundOrderResponses];

export type WarehouseApiRoutesOrdersAddItemToInboundOrderData = {
    body: InboundOrderItemCreateSchema;
    path: {
        /**
         * Order Code
         */
        order_code: string;
    };
    query?: never;
    url: '/api/v1/orders/{order_code}/items';
};

export type WarehouseApiRoutesOrdersAddItemToInboundOrderResponses = {
    /**
     * OK
     */
    200: CreateInboundOrderItemResponse;
};

export type WarehouseApiRoutesOrdersAddItemToInboundOrderResponse = WarehouseApiRoutesOrdersAddItemToInboundOrderResponses[keyof WarehouseApiRoutesOrdersAddItemToInboundOrderResponses];

export type WarehouseApiRoutesOrdersTransitionInboundOrderData = {
    body: InboundOrderTransitionSchema;
    path: {
        /**
         * Order Code
         */
        order_code: string;
    };
    query?: never;
    url: '/api/v1/orders/{order_code}/state';
};

export type WarehouseApiRoutesOrdersTransitionInboundOrderResponses = {
    /**
     * OK
     */
    200: GetInboundOrderResponse;
};

export type WarehouseApiRoutesOrdersTransitionInboundOrderResponse = WarehouseApiRoutesOrdersTransitionInboundOrderResponses[keyof WarehouseApiRoutesOrdersTransitionInboundOrderResponses];

export type WarehouseApiRoutesOrdersRemoveItemsFromInboundOrderData = {
    body?: never;
    path: {
        /**
         * Order Code
         */
        order_code: string;
        /**
         * Product Code
         */
        product_code: string;
    };
    query?: never;
    url: '/api/v1/orders/{order_code}/items/{product_code}';
};

export type WarehouseApiRoutesOrdersRemoveItemsFromInboundOrderResponses = {
    /**
     * OK
     */
    200: EmptyResponse;
};

export type WarehouseApiRoutesOrdersRemoveItemsFromInboundOrderResponse = WarehouseApiRoutesOrdersRemoveItemsFromInboundOrderResponses[keyof WarehouseApiRoutesOrdersRemoveItemsFromInboundOrderResponses];
