// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

/**
 * AuthData
 */
export type AuthData = {
    /**
     * User Id
     */
    user_id: number;
    /**
     * Username
     */
    username: string;
};

/**
 * SigninResponse
 */
export type SigninResponse = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Message
     */
    message: string;
    data?: AuthData | null;
};

/**
 * LoginFormSchema
 */
export type LoginFormSchema = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * SignoutResponse
 */
export type SignoutResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Message
     */
    message?: string | null;
    /**
     * Data
     */
    data?: null;
};

/**
 * WhoamiResponse
 */
export type WhoamiResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Message
     */
    message?: string | null;
    data: AuthData;
};

/**
 * GetWarehousesResponse
 */
export type GetWarehousesResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Message
     */
    message?: string | null;
    /**
     * Data
     */
    data: Array<WarehouseSchema>;
};

/**
 * WarehouseLocationSchema
 */
export type WarehouseLocationSchema = {
    /**
     * Created
     */
    created: string;
    /**
     * Changed
     */
    changed: string;
    /**
     * Code
     */
    code: string;
};

/**
 * WarehouseSchema
 */
export type WarehouseSchema = {
    /**
     * Created
     */
    created: string;
    /**
     * Changed
     */
    changed: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Locations
     */
    locations: Array<WarehouseLocationSchema>;
};

/**
 * GetWarehouseLocationResponse
 */
export type GetWarehouseLocationResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Message
     */
    message?: string | null;
    data: WarehouseLocationDetailSchema;
};

/**
 * StockItemSchema
 */
export type StockItemSchema = {
    /**
     * Created
     */
    created: string;
    /**
     * Changed
     */
    changed: string;
    /**
     * Name
     */
    name: string;
    /**
     * Code
     */
    code: string;
};

/**
 * WarehouseItemSchema
 * Atomic unit of the inventory - uniquely identifiable and trackable item in a warehouse
 */
export type WarehouseItemSchema = {
    /**
     * Created
     */
    created: string;
    /**
     * Changed
     */
    changed: string;
    /**
     * Code
     */
    code: string;
    stock_item: StockItemSchema;
    /**
     * Unit Of Measure
     */
    unit_of_measure: string;
    /**
     * Factor At Receipt
     */
    factor_at_receipt: number;
    /**
     * Remaining
     */
    remaining: number;
};

/**
 * WarehouseLocationDetailSchema
 */
export type WarehouseLocationDetailSchema = {
    /**
     * Created
     */
    created: string;
    /**
     * Changed
     */
    changed: string;
    /**
     * Code
     */
    code: string;
    /**
     * Items
     */
    items: Array<WarehouseItemSchema>;
};

/**
 * Input
 */
export type Input = {
    /**
     * Page
     */
    page?: number;
    /**
     * Page Size
     */
    page_size?: number;
};

/**
 * ConversionFactorSchema
 */
export type ConversionFactorSchema = {
    /**
     * Unit Of Measure
     */
    unit_of_measure: string;
    /**
     * Factor
     */
    factor: number;
};

/**
 * PagedProductSchema
 */
export type PagedProductSchema = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Message
     */
    message?: string | null;
    /**
     * Data
     */
    data: Array<ProductSchema>;
    /**
     * Count
     */
    count: number;
    /**
     * Next
     */
    next: number | null;
    /**
     * Previous
     */
    previous: number | null;
};

/**
 * ProductSchema
 */
export type ProductSchema = {
    /**
     * Created
     */
    created: string;
    /**
     * Changed
     */
    changed: string;
    /**
     * Name
     */
    name: string;
    /**
     * Code
     */
    code: string;
    /**
     * Type
     */
    type: string;
    /**
     * Unit
     */
    unit: string;
    /**
     * Group
     */
    group?: string | null;
    /**
     * Conversion Factors
     */
    conversion_factors: Array<ConversionFactorSchema>;
};

/**
 * GetProductResponse
 */
export type GetProductResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Message
     */
    message?: string | null;
    data: ProductSchema;
};

/**
 * GetProductWarehouseInfoResponse
 */
export type GetProductWarehouseInfoResponse = {
    /**
     * Success
     */
    success?: boolean;
    /**
     * Message
     */
    message?: string | null;
    /**
     * Data
     */
    data: Array<WarehouseExpandedSchema>;
};

/**
 * WarehouseExpandedSchema
 */
export type WarehouseExpandedSchema = {
    /**
     * Created
     */
    created: string;
    /**
     * Changed
     */
    changed: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Locations
     */
    locations: Array<WarehouseLocationDetailSchema>;
};

export type WarehouseApiRoutesAuthLoginUserData = {
    body: LoginFormSchema;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type WarehouseApiRoutesAuthLoginUserErrors = {
    /**
     * Unauthorized
     */
    401: SigninResponse;
};

export type WarehouseApiRoutesAuthLoginUserError = WarehouseApiRoutesAuthLoginUserErrors[keyof WarehouseApiRoutesAuthLoginUserErrors];

export type WarehouseApiRoutesAuthLoginUserResponses = {
    /**
     * OK
     */
    200: SigninResponse;
};

export type WarehouseApiRoutesAuthLoginUserResponse = WarehouseApiRoutesAuthLoginUserResponses[keyof WarehouseApiRoutesAuthLoginUserResponses];

export type WarehouseApiRoutesAuthLogoutUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type WarehouseApiRoutesAuthLogoutUserResponses = {
    /**
     * OK
     */
    200: SignoutResponse;
};

export type WarehouseApiRoutesAuthLogoutUserResponse = WarehouseApiRoutesAuthLogoutUserResponses[keyof WarehouseApiRoutesAuthLogoutUserResponses];

export type WarehouseApiRoutesAuthWhoamiData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/whoami';
};

export type WarehouseApiRoutesAuthWhoamiErrors = {
    /**
     * Unauthorized
     */
    401: SigninResponse;
};

export type WarehouseApiRoutesAuthWhoamiError = WarehouseApiRoutesAuthWhoamiErrors[keyof WarehouseApiRoutesAuthWhoamiErrors];

export type WarehouseApiRoutesAuthWhoamiResponses = {
    /**
     * OK
     */
    200: WhoamiResponse;
};

export type WarehouseApiRoutesAuthWhoamiResponse = WarehouseApiRoutesAuthWhoamiResponses[keyof WarehouseApiRoutesAuthWhoamiResponses];

export type WarehouseApiRoutesWarehouseGetWarehousesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/warehouses';
};

export type WarehouseApiRoutesWarehouseGetWarehousesResponses = {
    /**
     * OK
     */
    200: GetWarehousesResponse;
};

export type WarehouseApiRoutesWarehouseGetWarehousesResponse = WarehouseApiRoutesWarehouseGetWarehousesResponses[keyof WarehouseApiRoutesWarehouseGetWarehousesResponses];

export type WarehouseApiRoutesWarehouseGetWarehouseLocationData = {
    body?: never;
    path: {
        /**
         * Warehouse Location Code
         */
        warehouse_location_code: string;
    };
    query?: never;
    url: '/api/v1/locations/{warehouse_location_code}';
};

export type WarehouseApiRoutesWarehouseGetWarehouseLocationResponses = {
    /**
     * OK
     */
    200: GetWarehouseLocationResponse;
};

export type WarehouseApiRoutesWarehouseGetWarehouseLocationResponse = WarehouseApiRoutesWarehouseGetWarehouseLocationResponses[keyof WarehouseApiRoutesWarehouseGetWarehouseLocationResponses];

export type WarehouseApiRoutesProductGetProductsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Search Term
         */
        search_term?: string | null;
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/v1/products';
};

export type WarehouseApiRoutesProductGetProductsResponses = {
    /**
     * OK
     */
    200: PagedProductSchema;
};

export type WarehouseApiRoutesProductGetProductsResponse = WarehouseApiRoutesProductGetProductsResponses[keyof WarehouseApiRoutesProductGetProductsResponses];

export type WarehouseApiRoutesProductGetProductData = {
    body?: never;
    path: {
        /**
         * Product Code
         */
        product_code: string;
    };
    query?: never;
    url: '/api/v1/products/{product_code}';
};

export type WarehouseApiRoutesProductGetProductResponses = {
    /**
     * OK
     */
    200: GetProductResponse;
};

export type WarehouseApiRoutesProductGetProductResponse = WarehouseApiRoutesProductGetProductResponses[keyof WarehouseApiRoutesProductGetProductResponses];

export type WarehouseApiRoutesProductGetProductWarehouseInfoData = {
    body?: never;
    path: {
        /**
         * Product Code
         */
        product_code: string;
    };
    query?: never;
    url: '/api/v1/products/{product_code}/warehouse-info';
};

export type WarehouseApiRoutesProductGetProductWarehouseInfoResponses = {
    /**
     * OK
     */
    200: GetProductWarehouseInfoResponse;
};

export type WarehouseApiRoutesProductGetProductWarehouseInfoResponse = WarehouseApiRoutesProductGetProductWarehouseInfoResponses[keyof WarehouseApiRoutesProductGetProductWarehouseInfoResponses];
