# Generated by Django 5.2.6 on 2025-10-25 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehousemovement",
            name="location_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movements_from",
                to="warehouse.warehouselocation",
            ),
        ),
        migrations.AlterField(
            model_name="warehousemovement",
            name="location_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movements_to",
                to="warehouse.warehouselocation",
            ),
        ),
    ]
