# Generated by Django 5.2.6 on 2025-11-04 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="warehouseitem",
            old_name="stock_item",
            new_name="stock_product",
        ),
        migrations.AlterField(
            model_name="warehouseitem",
            name="lot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="warehouse.lot",
            ),
        ),
    ]
