# Generated by Django 5.2.6 on 2025-10-22 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0002_warehouseorderin_warehouseorderout_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehouselocation",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="locations",
                to="warehouse.warehouse",
            ),
        ),
    ]
