# Generated by Django 5.2.6 on 2025-11-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0002_rename_stock_item_warehouseitem_stock_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehouseitem",
            name="amount",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
