# Generated by Django 5.2.6 on 2025-10-22 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0003_alter_warehouselocation_warehouse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehouseitem",
            name="warehouse_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="warehouse.warehouselocation",
            ),
        ),
    ]
