# Generated by Django 5.2.6 on 2025-10-28 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0003_alter_warehouseitem_current_load_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productgroup",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="warehouse.productgroup",
            ),
        ),
    ]
