# Generated by Django 5.2.6 on 2025-11-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0003_alter_warehouseitem_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehouseitem",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
    ]
