# Generated by Django 5.2.6 on 2025-10-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0004_alter_productgroup_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouseitem",
            name="code",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
