# Generated by Django 5.2.6 on 2025-11-08 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0004_alter_warehouseitem_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="warehouse.packagetype"
            ),
        ),
    ]
