# Generated by Django 5.2.6 on 2025-10-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0005_warehouseitem_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehouseitem",
            name="code",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
