# Generated by Django 5.2.6 on 2025-11-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0005_alter_package_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packagetype",
            name="amount",
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
