# Generated by Django 5.2.6 on 2025-10-29 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0006_alter_warehouseitem_code"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="warehouseitem",
            name="load_or_location_exclusive",
        ),
        migrations.RemoveField(
            model_name="warehouseitem",
            name="current_load",
        ),
        migrations.AlterField(
            model_name="warehouseitem",
            name="warehouse_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="warehouse.warehouselocation",
            ),
        ),
    ]
