# Generated by Django 5.2.6 on 2025-11-12 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0007_incomingorder_incomingorderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="incomingorderitem",
            name="order",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="warehouse.incomingorder",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="incomingorder",
            name="external_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
