# Generated by Django 5.2.6 on 2025-10-29 20:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0008_customergroup_customer_person"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="owner_id",
        ),
    ]
