# Generated by Django 5.2.6 on 2025-11-13 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0008_incomingorderitem_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incomingorderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="warehouse.incomingorder",
            ),
        ),
    ]
