# Generated by Django 5.2.6 on 2025-12-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "warehouse",
            "0010_incomingorder_currency_incomingorderitem_unit_price_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="stockproduct",
            name="base_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="stockproduct",
            name="currency",
            field=models.CharField(
                choices=[
                    ("AED", "UAE Dirham"),
                    ("AFN", "Afghan Afghani"),
                    ("ALL", "Albanian Lek"),
                    ("AMD", "Armenian Dram"),
                    ("ANG", "Netherlands Antillean Guilder"),
                    ("AOA", "Angolan Kwanza"),
                    ("ARS", "Argentine Peso"),
                    ("AUD", "Australian Dollar"),
                    ("AWG", "Aruban Florin"),
                    ("AZN", "Azerbaijani Manat"),
                    ("BAM", "Bosnia and Herzegovina Convertible Mark"),
                    ("BBD", "Barbadian Dollar"),
                    ("BDT", "Bangladeshi Taka"),
                    ("BGN", "Bulgarian Lev"),
                    ("BHD", "Bahraini Dinar"),
                    ("BIF", "Burundian Franc"),
                    ("BMD", "Bermudian Dollar"),
                    ("BND", "Brunei Dollar"),
                    ("BOB", "Bolivian Boliviano"),
                    ("BRL", "Brazilian Real"),
                    ("BSD", "Bahamian Dollar"),
                    ("BTN", "Bhutanese Ngultrum"),
                    ("BWP", "Botswana Pula"),
                    ("BYN", "Belarusian Ruble"),
                    ("BZD", "Belize Dollar"),
                    ("CAD", "Canadian Dollar"),
                    ("CDF", "Congolese Franc"),
                    ("CHF", "Swiss Franc"),
                    ("CLP", "Chilean Peso"),
                    ("CNY", "Chinese Yuan"),
                    ("COP", "Colombian Peso"),
                    ("CRC", "Costa Rican Colón"),
                    ("CUP", "Cuban Peso"),
                    ("CVE", "Cape Verdean Escudo"),
                    ("CZK", "Czech Koruna"),
                    ("DJF", "Djiboutian Franc"),
                    ("DKK", "Danish Krone"),
                    ("DOP", "Dominican Peso"),
                    ("DZD", "Algerian Dinar"),
                    ("EGP", "Egyptian Pound"),
                    ("ERN", "Eritrean Nakfa"),
                    ("ETB", "Ethiopian Birr"),
                    ("EUR", "Euro"),
                    ("FJD", "Fijian Dollar"),
                    ("FKP", "Falkland Islands Pound"),
                    ("GBP", "Pound"),
                ],
                default="CZK",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="stockproduct",
            name="purchase_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="warehouseitem",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Amount of the stock product in stock product UOM",
                max_digits=10,
                null=True,
            ),
        ),
    ]
