# Generated by Django 5.2.6 on 2025-12-01 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0011_stockproduct_base_price_stockproduct_currency_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="warehouseitem",
            name="lot",
        ),
        migrations.AddField(
            model_name="warehouseitem",
            name="order_in",
            field=models.ForeignKey(
                blank=True,
                help_text="Order which brought the item into the warehouse",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="warehouse.warehouseorderin",
            ),
        ),
        migrations.AddField(
            model_name="warehouseorderin",
            name="code",
            field=models.CharField(default="aljwdawd", max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="warehouseitem",
            name="location",
            field=models.ForeignKey(
                help_text="Location where the physical item is stored in the warehouse",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="warehouse.warehouselocation",
            ),
        ),
        migrations.AlterField(
            model_name="warehouseitem",
            name="package",
            field=models.OneToOneField(
                blank=True,
                help_text="Packaging information - in case the item is packaged in some way (optional)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item",
                to="warehouse.package",
            ),
        ),
        migrations.AlterField(
            model_name="warehouseitem",
            name="stock_product",
            field=models.ForeignKey(
                help_text="Product information",
                on_delete=django.db.models.deletion.PROTECT,
                to="warehouse.stockproduct",
            ),
        ),
    ]
