# Generated by Django 5.2.6 on 2025-10-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0011_customertype_person_birth_date_person_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="profile_picture_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
