# Generated by Django 5.2.6 on 2025-10-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0012_alter_person_profile_picture_url"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Person",
            new_name="ContactPerson",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="price_type_code",
        ),
        migrations.AddField(
            model_name="customer",
            name="price_type",
            field=models.CharField(
                choices=[("FIRMA", "Company"), ("OSOBA", "Person")],
                default="FIRMY",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customer",
            name="customer_type",
            field=models.CharField(
                choices=[("FIRMY", "Companies")], default="FIRMA", max_length=50
            ),
            preserve_default=False,
        ),
    ]
