# Generated by Django 5.2.6 on 2025-12-01 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0012_remove_warehouseitem_lot_warehouseitem_order_in_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Lot",
        ),
        migrations.RemoveField(
            model_name="warehouseitem",
            name="package",
        ),
        migrations.AddField(
            model_name="warehouseitem",
            name="package_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Packaging information - in case the item is packaged in some way (optional)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="warehouse.packagetype",
            ),
        ),
    ]
