# Generated by Django 5.2.6 on 2025-10-30 14:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0013_rename_person_contactperson_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomerType",
        ),
        migrations.AlterModelOptions(
            name="contactperson",
            options={
                "ordering": ["last_name", "first_name"],
                "verbose_name": "Customer contact",
                "verbose_name_plural": "Customer contacts",
            },
        ),
    ]
