# Generated by Django 5.2.6 on 2025-12-01 16:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0013_delete_lot_remove_warehouseitem_package_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Package",
        ),
    ]
