# Generated by Django 5.2.6 on 2025-12-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0014_delete_package"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouseorderout",
            name="code",
            field=models.CharField(default="alwdjawd", max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
