# Generated by Django 5.2.6 on 2025-12-01 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0015_warehouseorderout_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouseorderin",
            name="order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="warehouse_order",
                to="warehouse.incomingorder",
            ),
        ),
    ]
