# Generated by Django 5.2.6 on 2025-12-03 09:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0017_incomingorder_state_alter_incomingorder_currency_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="IncomingOrder",
            new_name="InboundOrder",
        ),
        migrations.RenameModel(
            old_name="IncomingOrderItem",
            new_name="InboundOrderItem",
        ),
    ]
