# Generated by Django 5.2.6 on 2025-12-03 10:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0018_rename_incomingorder_inboundorder_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inboundorder",
            options={"ordering": ["-created"]},
        ),
    ]
