# Generated by Django 5.2.6 on 2025-12-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0019_alter_inboundorder_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockproduct",
            name="attributes",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
