# Generated by Django 5.2.6 on 2025-12-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0020_stockproduct_attributes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockproduct",
            name="attributes",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
