# Generated by Django 5.2.6 on 2025-12-03 14:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0021_alter_stockproduct_attributes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stockproduct",
            options={"ordering": ["code"]},
        ),
    ]
