# Generated by Django 5.2.6 on 2025-12-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0022_alter_stockproduct_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouseorderin",
            name="state",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("started", "Started"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=30,
            ),
        ),
    ]
