# Generated by Django 5.2.6 on 2025-12-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0023_warehouseorderin_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouselocation",
            name="is_putaway",
            field=models.BooleanField(default=False),
        ),
    ]
