# Generated by Django 5.2.6 on 2025-12-04 12:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0024_warehouselocation_is_putaway"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="warehouseorderin",
            options={"ordering": ["-created"]},
        ),
    ]
