# Generated by Django 5.2.6 on 2025-12-04 12:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0025_alter_warehouseorderin_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="warehouselocation",
            options={"ordering": ["code"]},
        ),
    ]
