# Generated by Django 5.2.6 on 2025-12-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0026_alter_warehouselocation_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockproduct",
            name="customs_declaration_group",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
