# Generated by Django 5.2.6 on 2025-12-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0027_stockproduct_customs_declaration_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehouseorderin",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("started", "Started"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=30,
            ),
        ),
    ]
