# Generated by Django 5.2.6 on 2026-01-25 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0028_alter_warehouseorderin_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inboundorder",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("receiving", "Receiving"),
                    ("putaway", "Put Away"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="warehouseorderin",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="warehouse_order",
                to="warehouse.inboundorder",
            ),
        ),
    ]
