# Generated by Django 5.2.6 on 2026-01-25 22:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0029_alter_inboundorder_state_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WarehouseOrderIn",
            new_name="InboundWarehouseOrder",
        ),
        migrations.RenameModel(
            old_name="WarehouseOrderOut",
            new_name="OutboundWarehouseOrder",
        ),
    ]
