# Generated by Django 5.2.6 on 2026-02-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0030_rename_warehouseorderin_inboundwarehouseorder_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehouseitem",
            name="amount",
            field=models.DecimalField(
                decimal_places=4,
                help_text="Amount of the stock product in stock product UOM",
                max_digits=10,
            ),
        ),
    ]
