# Generated by Django 5.2.6 on 2026-02-04 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0031_alter_warehouseitem_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packagetype",
            name="unit_of_measure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="package_types",
                to="warehouse.unitofmeasure",
            ),
        ),
    ]
