# Generated by Django 5.2.6 on 2026-02-07 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0033_creditnotesupplier_creditnotesupplieritem"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditnotesupplier",
            name="state",
            field=models.CharField(
                choices=[("draft", "Draft"), ("confirmed", "Confirmed")],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="creditnotesupplier",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credit_note",
                to="warehouse.inboundorder",
            ),
        ),
    ]
