# Generated by Django 5.2.6 on 2026-02-07 22:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0034_creditnotesupplier_state_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CreditNoteSupplier",
            new_name="CreditNoteToSupplier",
        ),
    ]
