# Generated by Django 5.2.6 on 2026-02-08 21:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0035_rename_creditnotesupplier_creditnotetosupplier"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CreditNoteSupplierItem",
            new_name="CreditNoteToSupplierItem",
        ),
    ]
