# Generated by Django 5.2.6 on 2026-02-08 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0036_rename_creditnotesupplieritem_creditnotetosupplieritem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehouseitem",
            name="order_in",
            field=models.ForeignKey(
                help_text="Order which brought the item into the warehouse",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="warehouse.inboundwarehouseorder",
            ),
        ),
    ]
