# Generated by Django 6.0.2 on 2026-02-16 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0037_alter_warehouseitem_order_in"),
    ]

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("changed", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="warehouseitem",
            name="tracking_level",
            field=models.CharField(
                choices=[
                    ("SERIALIZED_PIECE", "Individual Pieces"),
                    ("SERIALIZED_PACKAGE", "Individual Packages"),
                    ("BATCH", "Batch Tracked"),
                    ("FUNGIBLE", "Fully Fungible"),
                ],
                default="FUNGIBLE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="warehouseitem",
            name="code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Serial number - only for SERIALIZED_* levels",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="warehouseitem",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                help_text="Required for BATCH and SERIALIZED_* levels",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventory",
                to="warehouse.batch",
            ),
        ),
    ]
