# Generated by Django 6.0.2 on 2026-02-16 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0038_batch_warehouseitem_tracking_level_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="warehouseitem",
            name="order_in",
        ),
        migrations.CreateModel(
            name="InboundWarehouseOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("changed", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("amount", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="warehouse.inboundwarehouseorder",
                    ),
                ),
                (
                    "order_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="warehouse_order_item",
                        to="warehouse.inboundorderitem",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="warehouseitem",
            name="order_item_in",
            field=models.OneToOneField(
                blank=True,
                help_text="Order item which brought the item into the warehouse",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="warehouse_item",
                to="warehouse.inboundwarehouseorderitem",
            ),
        ),
    ]
