# Generated by Django 6.0.2 on 2026-02-16 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0039_remove_warehouseitem_order_in_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inboundwarehouseorderitem",
            name="code",
        ),
        migrations.AlterField(
            model_name="warehouseitem",
            name="order_item_in",
            field=models.OneToOneField(
                blank=True,
                help_text="Order item which brought the item into the warehouse",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="warehouse_items",
                to="warehouse.inboundwarehouseorderitem",
            ),
        ),
    ]
