# Generated by Django 6.0.2 on 2026-02-19 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("warehouse", "0040_remove_inboundwarehouseorderitem_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="warehouseitem",
            name="order_item_in",
        ),
        migrations.RemoveField(
            model_name="batch",
            name="code",
        ),
        migrations.RemoveField(
            model_name="warehouseitem",
            name="code",
        ),
        migrations.AddField(
            model_name="batch",
            name="description",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="warehouseitem",
            name="order_in",
            field=models.OneToOneField(
                blank=True,
                help_text="Order item which brought the item into the warehouse",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="warehouse_items",
                to="warehouse.inboundwarehouseorder",
            ),
        ),
        migrations.CreateModel(
            name="Barcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("changed", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(db_index=True, max_length=100, unique=True)),
                (
                    "barcode_type",
                    models.CharField(
                        choices=[
                            ("EAN13", "EAN-13"),
                            ("EAN8", "EAN-8"),
                            ("UPC", "UPC"),
                            ("GS1_128", "GS1-128"),
                            ("QR", "QR Code"),
                            ("SERIAL", "Serial Number"),
                            ("SSCC", "SSCC"),
                            ("CUSTOM", "Custom"),
                        ]
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="InboundWarehouseOrderItem",
        ),
        migrations.AddIndex(
            model_name="barcode",
            index=models.Index(fields=["code"], name="warehouse_b_code_b4e36e_idx"),
        ),
        migrations.AddIndex(
            model_name="barcode",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="warehouse_b_content_db4fe2_idx",
            ),
        ),
    ]
