# Generated by Django 6.0.2 on 2026-02-19 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "warehouse",
            "0041_remove_warehouseitem_order_item_in_remove_batch_code_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehouseitem",
            name="order_in",
            field=models.OneToOneField(
                blank=True,
                help_text="Order item which brought the item into the warehouse",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="warehouse.inboundwarehouseorder",
            ),
        ),
    ]
