# Generated by Django 6.0.2 on 2026-02-19 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0042_alter_warehouseitem_order_in"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehouseitem",
            name="order_in",
            field=models.ForeignKey(
                blank=True,
                help_text="Order item which brought the item into the warehouse",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="warehouse.inboundwarehouseorder",
            ),
        ),
    ]
