# Generated by Django 6.0.2 on 2026-02-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0043_alter_warehouseitem_order_in"),
    ]

    operations = [
        migrations.AddField(
            model_name="inboundorder",
            name="cancelled_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inboundorder",
            name="received_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inboundorder",
            name="requested_delivery_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="barcode",
            name="barcode_type",
            field=models.CharField(
                choices=[
                    ("EAN13", "EAN-13"),
                    ("EAN8", "EAN-8"),
                    ("UPC", "UPC"),
                    ("GS1_128", "GS1-128"),
                    ("QR", "QR Code"),
                    ("SERIAL", "Serial Number"),
                    ("SSCC", "SSCC"),
                    ("CUSTOM", "Custom"),
                ],
                max_length=10,
            ),
        ),
    ]
