# Generated by Django 6.0.2 on 2026-03-06 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0044_inboundorder_cancelled_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="warehousemovement",
            name="changed",
        ),
        migrations.RemoveField(
            model_name="warehousemovement",
            name="created",
        ),
        migrations.AddField(
            model_name="warehousemovement",
            name="amount",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="Amount of the stock product in stock product UOM",
                max_digits=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="warehousemovement",
            name="inbound_order_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="warehouse_movements",
                to="warehouse.inboundwarehouseorder",
            ),
        ),
        migrations.AddField(
            model_name="warehousemovement",
            name="moved_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="warehousemovement",
            name="outbound_order_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="warehouse_movements",
                to="warehouse.outboundwarehouseorder",
            ),
        ),
        migrations.AddField(
            model_name="warehousemovement",
            name="stock_product",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="warehouse_movements",
                to="warehouse.stockproduct",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="warehousemovement",
            name="item",
            field=models.ForeignKey(
                help_text="Track item ID for non-fungible items",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movements",
                to="warehouse.warehouseitem",
            ),
        ),
        migrations.AlterField(
            model_name="warehousemovement",
            name="location_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movements_from",
                to="warehouse.warehouselocation",
            ),
        ),
    ]
