# Generated by Django 6.0.2 on 2026-03-06 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0045_remove_warehousemovement_changed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehousemovement",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="warehouse.batch",
            ),
        ),
    ]
