# Generated by Django 6.0.2 on 2026-03-08 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("warehouse", "0047_inboundorderitem_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("changed", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("transition", "State Transition"),
                            ("access", "Access"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        help_text="The type of action performed.",
                        max_length=20,
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        db_index=True,
                        help_text="The primary key of the object being audited.",
                    ),
                ),
                (
                    "object_repr",
                    models.CharField(
                        help_text="A human-readable representation of the object at the time of the log.",
                        max_length=255,
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="A JSON diff of the changes made to the object.",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="The reason or justification for the action.",
                        null=True,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="The model of the object being audited.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who performed the action.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-created"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="warehouse_a_content_b32d20_idx",
                    )
                ],
            },
        ),
    ]
