# Generated by Django 6.0.2 on 2026-03-10 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0048_auditlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("changed", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StockProductPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("changed", models.DateTimeField(auto_now=True)),
                (
                    "price_type",
                    models.CharField(
                        choices=[
                            ("GROUP_DISCOUNT", "Generic group discount"),
                            ("CUSTOMER_DISCOUNT", "Customer discount"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_prices",
                        to="warehouse.customer",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="warehouse.pricegroup",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dynamic_prices",
                        to="warehouse.stockproduct",
                    ),
                ),
            ],
            options={
                "ordering": ["product", "price_type", "discount_percent"],
                "abstract": False,
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("discount_percent__gte", 0), ("discount_percent__lte", 100)
                        ),
                        name="warehouse_productprice_discount_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("customer__isnull", True),
                                ("group__isnull", False),
                                ("price_type", "GROUP_DISCOUNT"),
                            ),
                            models.Q(
                                ("customer__isnull", False),
                                ("group__isnull", True),
                                ("price_type", "CUSTOMER_DISCOUNT"),
                            ),
                            _connector="OR",
                        ),
                        name="warehouse_productprice_target_by_type",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("group__isnull", False), ("price_type", "GROUP_DISCOUNT")
                        ),
                        fields=("product", "group"),
                        name="warehouse_unique_product_group_discount",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("customer__isnull", False),
                            ("price_type", "CUSTOMER_DISCOUNT"),
                        ),
                        fields=("product", "customer"),
                        name="warehouse_unique_product_customer_discount",
                    ),
                ],
            },
        ),
    ]
