# Generated by Django 6.0.2 on 2026-03-12 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0050_seed_default_price_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="inboundwarehouseorder",
            name="primary_order",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary order that this order is derived from",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="derived_orders",
                to="warehouse.inboundwarehouseorder",
            ),
        ),
    ]
