# Generated by Django 6.0.2 on 2026-03-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0051_inboundwarehouseorder_primary_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inboundwarehouseorder",
            name="state",
            field=models.CharField(
                choices=[
                    ("in transit", "In Transit"),
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("started", "Started"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=30,
            ),
        ),
    ]
