# Generated by Django 6.0.2 on 2026-03-31 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0052_alter_inboundwarehouseorder_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inboundwarehouseorder",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="warehouse_orders",
                to="warehouse.inboundorder",
            ),
        ),
    ]
