# Generated by Django 6.0.2 on 2026-03-31 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0053_inbound_warehouse_order_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="inboundorderitem",
            name="total_price",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
