# Generated by Django 6.0.2 on 2026-04-01 09:56

import apps.warehouse.models.orders
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0054_inbound_order_item_total_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoicePaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("changed", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("changed", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("issued_date", models.DateField()),
                ("due_date", models.DateField()),
                (
                    "external_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("taxable_supply_date", models.DateField()),
                ("paid_date", models.DateField(blank=True, null=True)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("CZK", "Czech Koruna"),
                            ("AED", "UAE Dirham"),
                            ("AFN", "Afghan Afghani"),
                            ("ALL", "Albanian Lek"),
                            ("AMD", "Armenian Dram"),
                            ("ANG", "Netherlands Antillean Guilder"),
                            ("AOA", "Angolan Kwanza"),
                            ("ARS", "Argentine Peso"),
                            ("AUD", "Australian Dollar"),
                            ("AWG", "Aruban Florin"),
                            ("AZN", "Azerbaijani Manat"),
                            ("BAM", "Bosnia and Herzegovina Convertible Mark"),
                            ("BBD", "Barbadian Dollar"),
                            ("BDT", "Bangladeshi Taka"),
                            ("BGN", "Bulgarian Lev"),
                            ("BHD", "Bahraini Dinar"),
                            ("BIF", "Burundian Franc"),
                            ("BMD", "Bermudian Dollar"),
                            ("BND", "Brunei Dollar"),
                            ("BOB", "Bolivian Boliviano"),
                            ("BRL", "Brazilian Real"),
                            ("BSD", "Bahamian Dollar"),
                            ("BTN", "Bhutanese Ngultrum"),
                            ("BWP", "Botswana Pula"),
                            ("BYN", "Belarusian Ruble"),
                            ("BZD", "Belize Dollar"),
                            ("CAD", "Canadian Dollar"),
                            ("CDF", "Congolese Franc"),
                            ("CHF", "Swiss Franc"),
                            ("CLP", "Chilean Peso"),
                            ("CNY", "Chinese Yuan"),
                            ("COP", "Colombian Peso"),
                            ("CRC", "Costa Rican Colón"),
                            ("CUP", "Cuban Peso"),
                            ("CVE", "Cape Verdean Escudo"),
                            ("DJF", "Djiboutian Franc"),
                            ("DKK", "Danish Krone"),
                            ("DOP", "Dominican Peso"),
                            ("DZD", "Algerian Dinar"),
                            ("EGP", "Egyptian Pound"),
                            ("ERN", "Eritrean Nakfa"),
                            ("ETB", "Ethiopian Birr"),
                            ("EUR", "Euro"),
                            ("FJD", "Fijian Dollar"),
                            ("FKP", "Falkland Islands Pound"),
                            ("GBP", "Pound"),
                        ],
                        default="CZK",
                        max_length=3,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.warehouse.models.orders.invoice_document_upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            )
                        ],
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_invoices",
                        to="warehouse.customer",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplier_invoices",
                        to="warehouse.customer",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="warehouse.invoicepaymentmethod",
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_date", "-created"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="inboundorder",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inbound_orders",
                to="warehouse.invoice",
            ),
        ),
    ]
