# Generated by Django 6.0.2 on 2026-04-06 21:24

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0055_invoicepaymentmethod_invoice_inboundorder_invoice"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditNoteToCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("changed", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("reason", models.TextField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[("draft", "Draft"), ("confirmed", "Confirmed")],
                        default="draft",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="outboundwarehouseorder",
            options={"ordering": ["-created"]},
        ),
        migrations.AddField(
            model_name="outboundwarehouseorder",
            name="primary_order",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary order that this order is derived from",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="derived_orders",
                to="warehouse.outboundwarehouseorder",
            ),
        ),
        migrations.AddField(
            model_name="outboundwarehouseorder",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("started", "Started"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="CreditNoteToCustomerItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("changed", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "credit_note",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="warehouse.creditnotetocustomer",
                    ),
                ),
                (
                    "stock_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.stockproduct",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OutboundOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("changed", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "external_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("CZK", "Czech Koruna"),
                            ("AED", "UAE Dirham"),
                            ("AFN", "Afghan Afghani"),
                            ("ALL", "Albanian Lek"),
                            ("AMD", "Armenian Dram"),
                            ("ANG", "Netherlands Antillean Guilder"),
                            ("AOA", "Angolan Kwanza"),
                            ("ARS", "Argentine Peso"),
                            ("AUD", "Australian Dollar"),
                            ("AWG", "Aruban Florin"),
                            ("AZN", "Azerbaijani Manat"),
                            ("BAM", "Bosnia and Herzegovina Convertible Mark"),
                            ("BBD", "Barbadian Dollar"),
                            ("BDT", "Bangladeshi Taka"),
                            ("BGN", "Bulgarian Lev"),
                            ("BHD", "Bahraini Dinar"),
                            ("BIF", "Burundian Franc"),
                            ("BMD", "Bermudian Dollar"),
                            ("BND", "Brunei Dollar"),
                            ("BOB", "Bolivian Boliviano"),
                            ("BRL", "Brazilian Real"),
                            ("BSD", "Bahamian Dollar"),
                            ("BTN", "Bhutanese Ngultrum"),
                            ("BWP", "Botswana Pula"),
                            ("BYN", "Belarusian Ruble"),
                            ("BZD", "Belize Dollar"),
                            ("CAD", "Canadian Dollar"),
                            ("CDF", "Congolese Franc"),
                            ("CHF", "Swiss Franc"),
                            ("CLP", "Chilean Peso"),
                            ("CNY", "Chinese Yuan"),
                            ("COP", "Colombian Peso"),
                            ("CRC", "Costa Rican Colón"),
                            ("CUP", "Cuban Peso"),
                            ("CVE", "Cape Verdean Escudo"),
                            ("DJF", "Djiboutian Franc"),
                            ("DKK", "Danish Krone"),
                            ("DOP", "Dominican Peso"),
                            ("DZD", "Algerian Dinar"),
                            ("EGP", "Egyptian Pound"),
                            ("ERN", "Eritrean Nakfa"),
                            ("ETB", "Ethiopian Birr"),
                            ("EUR", "Euro"),
                            ("FJD", "Fijian Dollar"),
                            ("FKP", "Falkland Islands Pound"),
                            ("GBP", "Pound"),
                        ],
                        default="CZK",
                        max_length=3,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("picking", "Picking"),
                            ("packing", "Packing"),
                            ("shipping", "Shipping"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "requested_delivery_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("cancelled_date", models.DateTimeField(blank=True, null=True)),
                ("fulfilled_date", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.customer",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outbound_orders",
                        to="warehouse.invoice",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="creditnotetocustomer",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credit_note",
                to="warehouse.outboundorder",
            ),
        ),
        migrations.AddField(
            model_name="outboundwarehouseorder",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="warehouse_orders",
                to="warehouse.outboundorder",
            ),
        ),
        migrations.CreateModel(
            name="OutboundOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("changed", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=4, max_digits=10)),
                ("index", models.PositiveIntegerField(default=0)),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="warehouse.outboundorder",
                    ),
                ),
                (
                    "stock_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.stockproduct",
                    ),
                ),
            ],
            options={
                "ordering": ["index", "created"],
                "abstract": False,
            },
        ),
    ]
