# Generated by Django 6.0.2 on 2026-04-12 19:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0057_global_discount_groups_refactor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pricegroup",
            options={"ordering": ["code"]},
        ),
    ]
