# Generated by Django 6.0.2 on 2026-04-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0058_alter_pricegroup_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditnotetocustomer",
            name="state",
            field=models.PositiveIntegerField(
                choices=[(1, "Draft"), (2, "Confirmed")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="creditnotetosupplier",
            name="state",
            field=models.PositiveIntegerField(
                choices=[(1, "Draft"), (2, "Confirmed")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="inboundorder",
            name="state",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "Draft"),
                    (2, "Submitted"),
                    (3, "Receiving"),
                    (4, "Put Away"),
                    (5, "Completed"),
                    (6, "Cancelled"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="inboundwarehouseorder",
            name="state",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "In Transit"),
                    (2, "Draft"),
                    (3, "Pending"),
                    (4, "Started"),
                    (5, "Completed"),
                    (6, "Cancelled"),
                ],
                default=2,
            ),
        ),
        migrations.AlterField(
            model_name="outboundorder",
            name="state",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "Draft"),
                    (2, "Submitted"),
                    (3, "Picking"),
                    (4, "Packing"),
                    (5, "Shipping"),
                    (6, "Completed"),
                    (7, "Cancelled"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="outboundwarehouseorder",
            name="state",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "Draft"),
                    (2, "Pending"),
                    (3, "Started"),
                    (4, "Completed"),
                    (5, "Cancelled"),
                ],
                default=1,
            ),
        ),
    ]
