# Generated by Django 6.0.2 on 2026-04-12 20:36

from django.db import migrations


def convert_states_forward(apps, schema_editor):
    """Convert string state values to integers"""

    InboundOrder = apps.get_model("warehouse", "InboundOrder")
    for obj in InboundOrder.objects.all():
        mapping = {
            "draft": 1,
            "submitted": 2,
            "receiving": 3,
            "putaway": 4,
            "completed": 5,
            "cancelled": 6,
        }
        obj.state = mapping.get(obj.state, obj.state)
        obj.save(update_fields=["state"])

    OutboundOrder = apps.get_model("warehouse", "OutboundOrder")
    for obj in OutboundOrder.objects.all():
        mapping = {
            "draft": 1,
            "submitted": 2,
            "picking": 3,
            "packing": 4,
            "shipping": 5,
            "completed": 6,
            "cancelled": 7,
        }
        obj.state = mapping.get(obj.state, obj.state)
        obj.save(update_fields=["state"])

    CreditNoteToSupplier = apps.get_model("warehouse", "CreditNoteToSupplier")
    for obj in CreditNoteToSupplier.objects.all():
        mapping = {"draft": 1, "confirmed": 2}
        obj.state = mapping.get(obj.state, obj.state)
        obj.save(update_fields=["state"])

    CreditNoteToCustomer = apps.get_model("warehouse", "CreditNoteToCustomer")
    for obj in CreditNoteToCustomer.objects.all():
        mapping = {"draft": 1, "confirmed": 2}
        obj.state = mapping.get(obj.state, obj.state)
        obj.save(update_fields=["state"])

    InboundWarehouseOrder = apps.get_model("warehouse", "InboundWarehouseOrder")
    for obj in InboundWarehouseOrder.objects.all():
        mapping = {
            "in transit": 1,
            "draft": 2,
            "pending": 3,
            "started": 4,
            "completed": 5,
            "cancelled": 6,
        }
        obj.state = mapping.get(obj.state, obj.state)
        obj.save(update_fields=["state"])

    OutboundWarehouseOrder = apps.get_model("warehouse", "OutboundWarehouseOrder")
    for obj in OutboundWarehouseOrder.objects.all():
        mapping = {
            "draft": 1,
            "pending": 2,
            "started": 3,
            "completed": 4,
            "cancelled": 5,
        }
        obj.state = mapping.get(obj.state, obj.state)
        obj.save(update_fields=["state"])


def convert_states_backward(apps, schema_editor):
    """Revert integer state values back to strings"""

    InboundOrder = apps.get_model("warehouse", "InboundOrder")
    for obj in InboundOrder.objects.all():
        mapping = {
            1: "draft",
            2: "submitted",
            3: "receiving",
            4: "putaway",
            5: "completed",
            6: "cancelled",
        }
        obj.state = mapping.get(obj.state, obj.state)
        obj.save(update_fields=["state"])

    OutboundOrder = apps.get_model("warehouse", "OutboundOrder")
    for obj in OutboundOrder.objects.all():
        mapping = {
            1: "draft",
            2: "submitted",
            3: "picking",
            4: "packing",
            5: "shipping",
            6: "completed",
            7: "cancelled",
        }
        obj.state = mapping.get(obj.state, obj.state)
        obj.save(update_fields=["state"])

    CreditNoteToSupplier = apps.get_model("warehouse", "CreditNoteToSupplier")
    for obj in CreditNoteToSupplier.objects.all():
        mapping = {1: "draft", 2: "confirmed"}
        obj.state = mapping.get(obj.state, obj.state)
        obj.save(update_fields=["state"])

    CreditNoteToCustomer = apps.get_model("warehouse", "CreditNoteToCustomer")
    for obj in CreditNoteToCustomer.objects.all():
        mapping = {1: "draft", 2: "confirmed"}
        obj.state = mapping.get(obj.state, obj.state)
        obj.save(update_fields=["state"])

    InboundWarehouseOrder = apps.get_model("warehouse", "InboundWarehouseOrder")
    for obj in InboundWarehouseOrder.objects.all():
        mapping = {
            1: "in transit",
            2: "draft",
            3: "pending",
            4: "started",
            5: "completed",
            6: "cancelled",
        }
        obj.state = mapping.get(obj.state, obj.state)
        obj.save(update_fields=["state"])

    OutboundWarehouseOrder = apps.get_model("warehouse", "OutboundWarehouseOrder")
    for obj in OutboundWarehouseOrder.objects.all():
        mapping = {
            1: "draft",
            2: "pending",
            3: "started",
            4: "completed",
            5: "cancelled",
        }
        obj.state = mapping.get(obj.state, obj.state)
        obj.save(update_fields=["state"])


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0059_alter_creditnotetocustomer_state_and_more"),
    ]

    operations = [
        migrations.RunPython(convert_states_forward, convert_states_backward),
    ]
