# Generated by Django 6.0.2 on 2026-04-14 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0061_stockproductprice_fixed_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="inboundwarehouseorder",
            name="pickup_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Location where goods are staged upon arrival confirmation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inbound_pickup_orders",
                to="warehouse.warehouselocation",
            ),
        ),
        migrations.CreateModel(
            name="InboundWarehouseOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("changed", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "tracking_level",
                    models.CharField(
                        choices=[
                            ("SERIALIZED_PIECE", "Individual Pieces"),
                            ("SERIALIZED_PACKAGE", "Individual Packages"),
                            ("BATCH", "Batch Tracked"),
                            ("FUNGIBLE", "Fully Fungible"),
                        ],
                        default="FUNGIBLE",
                        max_length=20,
                    ),
                ),
                (
                    "unit_price_at_receipt",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Unit price frozen from the purchase order at arrival confirmation",
                        max_digits=10,
                    ),
                ),
                ("index", models.PositiveIntegerField(default=0)),
                (
                    "batch_barcode",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "package_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="warehouse.packagetype",
                    ),
                ),
                (
                    "stock_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.stockproduct",
                    ),
                ),
                (
                    "warehouse_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="warehouse.inboundwarehouseorder",
                    ),
                ),
            ],
            options={
                "ordering": ["index", "created"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="warehouseitem",
            name="source_order_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Frozen snapshot line that produced this item (set at confirmation, never changed)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="warehouse_items",
                to="warehouse.inboundwarehouseorderitem",
            ),
        ),
    ]
