# Generated by Django 6.0.2 on 2026-04-16 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0062_inboundwarehouseorder_pickup_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="outboundorderitem",
            name="desired_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="outbound_order_items",
                to="warehouse.batch",
            ),
        ),
        migrations.AddField(
            model_name="outboundorderitem",
            name="desired_package_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="outbound_order_items",
                to="warehouse.packagetype",
            ),
        ),
        migrations.CreateModel(
            name="OutboundWarehouseOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("changed", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=4, max_digits=10)),
                ("index", models.PositiveIntegerField(default=0)),
                (
                    "desired_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outbound_warehouse_order_items",
                        to="warehouse.batch",
                    ),
                ),
                (
                    "desired_package_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outbound_warehouse_order_items",
                        to="warehouse.packagetype",
                    ),
                ),
                (
                    "source_order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouse_order_items",
                        to="warehouse.outboundorderitem",
                    ),
                ),
                (
                    "stock_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.stockproduct",
                    ),
                ),
                (
                    "warehouse_item",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outbound_assignment",
                        to="warehouse.warehouseitem",
                    ),
                ),
                (
                    "warehouse_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="warehouse.outboundwarehouseorder",
                    ),
                ),
            ],
            options={
                "ordering": ["index", "created"],
                "abstract": False,
            },
        ),
    ]
