# Generated by Django 6.0.2 on 2026-04-22 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0063_outboundorderitem_desired_batch_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="default_payment_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_for_customers",
                to="warehouse.invoicepaymentmethod",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="is_self",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False), ("is_self", True)),
                fields=("is_self",),
                name="warehouse_single_self_customer",
            ),
        ),
    ]
