# Generated by Django 6.0.2 on 2026-04-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0065_alter_outboundorder_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="invoice_due_days",
            field=models.IntegerField(default=14),
        ),
    ]
