# Generated by Django 6.0.2 on 2026-04-28 20:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0066_alter_customer_invoice_due_days"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventorySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("changed", models.DateTimeField(auto_now=True)),
                (
                    "captured_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "trigger_source",
                    models.CharField(
                        choices=[("manual", "Manual"), ("scheduled", "Scheduled")],
                        default="manual",
                        max_length=32,
                    ),
                ),
                ("cadence", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "bucket_key",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("line_count", models.PositiveIntegerField(default=0)),
                (
                    "purchase_totals_by_currency",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "receipt_totals_by_currency",
                    models.JSONField(blank=True, default=dict),
                ),
                ("receipt_unpriced_line_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-captured_at", "-created"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("bucket_key__isnull", False),
                            ("cadence__isnull", False),
                            ("trigger_source", "scheduled"),
                        ),
                        fields=("trigger_source", "cadence", "bucket_key"),
                        name="warehouse_inventorysnapshot_scheduled_bucket_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="InventorySnapshotLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("changed", models.DateTimeField(auto_now=True)),
                ("warehouse_item_id_at_snapshot", models.PositiveBigIntegerField()),
                ("product_code", models.CharField(max_length=255)),
                ("product_name", models.CharField(max_length=255)),
                ("location_code", models.CharField(max_length=50)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=10)),
                ("unit_of_measure", models.CharField(max_length=64)),
                (
                    "tracking_level",
                    models.CharField(
                        choices=[
                            ("SERIALIZED_PIECE", "Individual Pieces"),
                            ("SERIALIZED_PACKAGE", "Individual Packages"),
                            ("BATCH", "Batch Tracked"),
                            ("FUNGIBLE", "Fully Fungible"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "purchase_currency",
                    models.CharField(
                        choices=[
                            ("CZK", "Czech Koruna"),
                            ("AED", "UAE Dirham"),
                            ("AFN", "Afghan Afghani"),
                            ("ALL", "Albanian Lek"),
                            ("AMD", "Armenian Dram"),
                            ("ANG", "Netherlands Antillean Guilder"),
                            ("AOA", "Angolan Kwanza"),
                            ("ARS", "Argentine Peso"),
                            ("AUD", "Australian Dollar"),
                            ("AWG", "Aruban Florin"),
                            ("AZN", "Azerbaijani Manat"),
                            ("BAM", "Bosnia and Herzegovina Convertible Mark"),
                            ("BBD", "Barbadian Dollar"),
                            ("BDT", "Bangladeshi Taka"),
                            ("BGN", "Bulgarian Lev"),
                            ("BHD", "Bahraini Dinar"),
                            ("BIF", "Burundian Franc"),
                            ("BMD", "Bermudian Dollar"),
                            ("BND", "Brunei Dollar"),
                            ("BOB", "Bolivian Boliviano"),
                            ("BRL", "Brazilian Real"),
                            ("BSD", "Bahamian Dollar"),
                            ("BTN", "Bhutanese Ngultrum"),
                            ("BWP", "Botswana Pula"),
                            ("BYN", "Belarusian Ruble"),
                            ("BZD", "Belize Dollar"),
                            ("CAD", "Canadian Dollar"),
                            ("CDF", "Congolese Franc"),
                            ("CHF", "Swiss Franc"),
                            ("CLP", "Chilean Peso"),
                            ("CNY", "Chinese Yuan"),
                            ("COP", "Colombian Peso"),
                            ("CRC", "Costa Rican Colón"),
                            ("CUP", "Cuban Peso"),
                            ("CVE", "Cape Verdean Escudo"),
                            ("DJF", "Djiboutian Franc"),
                            ("DKK", "Danish Krone"),
                            ("DOP", "Dominican Peso"),
                            ("DZD", "Algerian Dinar"),
                            ("EGP", "Egyptian Pound"),
                            ("ERN", "Eritrean Nakfa"),
                            ("ETB", "Ethiopian Birr"),
                            ("EUR", "Euro"),
                            ("FJD", "Fijian Dollar"),
                            ("FKP", "Falkland Islands Pound"),
                            ("GBP", "Pound"),
                        ],
                        default="CZK",
                        max_length=3,
                    ),
                ),
                (
                    "purchase_unit_price",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                (
                    "purchase_line_value",
                    models.DecimalField(decimal_places=4, max_digits=14),
                ),
                (
                    "receipt_currency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CZK", "Czech Koruna"),
                            ("AED", "UAE Dirham"),
                            ("AFN", "Afghan Afghani"),
                            ("ALL", "Albanian Lek"),
                            ("AMD", "Armenian Dram"),
                            ("ANG", "Netherlands Antillean Guilder"),
                            ("AOA", "Angolan Kwanza"),
                            ("ARS", "Argentine Peso"),
                            ("AUD", "Australian Dollar"),
                            ("AWG", "Aruban Florin"),
                            ("AZN", "Azerbaijani Manat"),
                            ("BAM", "Bosnia and Herzegovina Convertible Mark"),
                            ("BBD", "Barbadian Dollar"),
                            ("BDT", "Bangladeshi Taka"),
                            ("BGN", "Bulgarian Lev"),
                            ("BHD", "Bahraini Dinar"),
                            ("BIF", "Burundian Franc"),
                            ("BMD", "Bermudian Dollar"),
                            ("BND", "Brunei Dollar"),
                            ("BOB", "Bolivian Boliviano"),
                            ("BRL", "Brazilian Real"),
                            ("BSD", "Bahamian Dollar"),
                            ("BTN", "Bhutanese Ngultrum"),
                            ("BWP", "Botswana Pula"),
                            ("BYN", "Belarusian Ruble"),
                            ("BZD", "Belize Dollar"),
                            ("CAD", "Canadian Dollar"),
                            ("CDF", "Congolese Franc"),
                            ("CHF", "Swiss Franc"),
                            ("CLP", "Chilean Peso"),
                            ("CNY", "Chinese Yuan"),
                            ("COP", "Colombian Peso"),
                            ("CRC", "Costa Rican Colón"),
                            ("CUP", "Cuban Peso"),
                            ("CVE", "Cape Verdean Escudo"),
                            ("DJF", "Djiboutian Franc"),
                            ("DKK", "Danish Krone"),
                            ("DOP", "Dominican Peso"),
                            ("DZD", "Algerian Dinar"),
                            ("EGP", "Egyptian Pound"),
                            ("ERN", "Eritrean Nakfa"),
                            ("ETB", "Ethiopian Birr"),
                            ("EUR", "Euro"),
                            ("FJD", "Fijian Dollar"),
                            ("FKP", "Falkland Islands Pound"),
                            ("GBP", "Pound"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "receipt_unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "receipt_line_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                ("receipt_price_available", models.BooleanField(default=False)),
                (
                    "receipt_price_fallback_reason",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_snapshot_lines",
                        to="warehouse.warehouselocation",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="warehouse.inventorysnapshot",
                    ),
                ),
                (
                    "source_order_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_snapshot_lines",
                        to="warehouse.inboundwarehouseorderitem",
                    ),
                ),
                (
                    "stock_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_snapshot_lines",
                        to="warehouse.stockproduct",
                    ),
                ),
                (
                    "warehouse_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_snapshot_lines",
                        to="warehouse.warehouseitem",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "product_code",
                    "location_code",
                    "warehouse_item_id_at_snapshot",
                ],
                "abstract": False,
            },
        ),
    ]
