# Generated by Django 6.0.2 on 2026-05-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0069_stockproduct_no_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="outboundwarehouseorderitem",
            name="price_at_shipment",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Total cost at shipment time: amount × avg purchase price at the moment of picking. Frozen for tax/accounting.",
                max_digits=14,
                null=True,
            ),
        ),
    ]
