# Generated by Django 6.0.5 on 2026-05-14 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0071_outboundorder_calculation_code_and_state_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockproduct",
            name="disallow_unpacking",
            field=models.BooleanField(
                default=False,
                help_text="Prevent unpacking packages during outbound picking",
            ),
        ),
        migrations.AddField(
            model_name="warehouseitem",
            name="unpacked_from",
            field=models.ForeignKey(
                blank=True,
                help_text="Source package if created by unpacking",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unpacked_items",
                to="warehouse.warehouseitem",
            ),
        ),
    ]
