# Generated by Django 6.0.5 on 2026-06-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0072_stockproduct_disallow_unpacking_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="printer",
            name="ip",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="printer",
            name="port",
            field=models.PositiveIntegerField(default=9100),
        ),
    ]
