# Generated by Django 6.0.5 on 2026-06-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0073_printer_ip_port"),
    ]

    operations = [
        migrations.AddField(
            model_name="printer",
            name="dpi",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
