# Generated by Django 6.0.5 on 2026-06-18 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0074_printer_dpi"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManufacturingOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("changed", models.DateTimeField(auto_now=True)),
                ("in_amount", models.DecimalField(decimal_places=4, max_digits=10)),
                ("out_amount", models.DecimalField(decimal_places=4, max_digits=10)),
                ("index", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["index", "created"],
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="inboundwarehouseorder",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="warehouse_orders",
                to="warehouse.inboundorder",
            ),
        ),
        migrations.AlterField(
            model_name="outboundwarehouseorderitem",
            name="source_order_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="warehouse_order_items",
                to="warehouse.outboundorderitem",
            ),
        ),
        migrations.CreateModel(
            name="ManufacturingOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("changed", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "state",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Draft"),
                            (2, "Confirmed"),
                            (3, "In Progress"),
                            (4, "Completed"),
                            (5, "Cancelled"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "is_external",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the work is done by an external contractor",
                    ),
                ),
                ("cancelled_date", models.DateTimeField(blank=True, null=True)),
                ("completed_date", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Internal department or external contractor performing the work",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manufacturing_orders_as_customer",
                        to="warehouse.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="inboundwarehouseorder",
            name="manufacturing_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inbound_warehouse_orders",
                to="warehouse.manufacturingorder",
            ),
        ),
        migrations.AddField(
            model_name="outboundwarehouseorder",
            name="manufacturing_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="outbound_warehouse_orders",
                to="warehouse.manufacturingorder",
            ),
        ),
        migrations.AddConstraint(
            model_name="inboundwarehouseorder",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("manufacturing_order__isnull", True), ("order__isnull", False)
                    ),
                    models.Q(
                        ("manufacturing_order__isnull", False), ("order__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="inbound_warehouse_order_one_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="outboundwarehouseorder",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("manufacturing_order__isnull", True), ("order__isnull", False)
                    ),
                    models.Q(
                        ("manufacturing_order__isnull", False), ("order__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="outbound_warehouse_order_one_parent",
            ),
        ),
        migrations.AddField(
            model_name="manufacturingorderitem",
            name="in_product",
            field=models.ForeignKey(
                help_text="Product sent to the customer (consumed)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mfg_order_in_items",
                to="warehouse.stockproduct",
            ),
        ),
        migrations.AddField(
            model_name="manufacturingorderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="warehouse.manufacturingorder",
            ),
        ),
        migrations.AddField(
            model_name="manufacturingorderitem",
            name="out_product",
            field=models.ForeignKey(
                help_text="Product returned from the customer (produced)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mfg_order_out_items",
                to="warehouse.stockproduct",
            ),
        ),
        migrations.AddField(
            model_name="outboundwarehouseorderitem",
            name="source_manufacturing_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="warehouse_order_items",
                to="warehouse.manufacturingorderitem",
            ),
        ),
    ]
