# Generated by Django 6.0.5 on 2026-06-19 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0075_manufacturing_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturingorder",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                help_text="Supplier performing the manufacturing service",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="manufacturing_orders_as_supplier",
                to="warehouse.customer",
            ),
        ),
    ]
