# Generated by Django 6.0.5 on 2026-06-20 19:18

import apps.warehouse.models.customer
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0076_manufacturing_order_manufacturer"),
    ]

    operations = [
        migrations.AddField(
            model_name="inboundorder",
            name="customer",
            field=models.ForeignKey(
                default=apps.warehouse.models.customer.Customer.get_ghost_customer,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="inbound_orders_as_customer",
                to="warehouse.customer",
            ),
        ),
        migrations.AddField(
            model_name="outboundorder",
            name="supplier",
            field=models.ForeignKey(
                default=apps.warehouse.models.customer.Customer.get_ghost_customer,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="outbound_orders_as_customer",
                to="warehouse.customer",
            ),
        ),
        migrations.AlterField(
            model_name="inboundorder",
            name="supplier",
            field=models.ForeignKey(
                default=apps.warehouse.models.customer.Customer.get_ghost_customer,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="inbound_orders_as_supplier",
                to="warehouse.customer",
            ),
        ),
        migrations.AlterField(
            model_name="manufacturingorder",
            name="customer",
            field=models.ForeignKey(
                default=apps.warehouse.models.customer.Customer.get_ghost_customer,
                help_text="Internal department or external contractor performing the work",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="manufacturing_orders_as_customer",
                to="warehouse.customer",
            ),
        ),
        migrations.AlterField(
            model_name="manufacturingorder",
            name="supplier",
            field=models.ForeignKey(
                default=apps.warehouse.models.customer.Customer.get_ghost_customer,
                help_text="Supplier performing the manufacturing service",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="manufacturing_orders_as_supplier",
                to="warehouse.customer",
            ),
        ),
        migrations.AlterField(
            model_name="outboundorder",
            name="customer",
            field=models.ForeignKey(
                default=apps.warehouse.models.customer.Customer.get_ghost_customer,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="outbound_orders_as_supplier",
                to="warehouse.customer",
            ),
        ),
    ]
