# Generated by Django 6.0.5 on 2026-07-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0079_warehouseitem_location_nullable"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="inboundorderitem",
            constraint=models.UniqueConstraint(
                fields=("order", "index"), name="unique_inbound_order_item_order_index"
            ),
        ),
        migrations.AddConstraint(
            model_name="outboundorderitem",
            constraint=models.UniqueConstraint(
                fields=("order", "index"), name="unique_outbound_order_item_order_index"
            ),
        ),
    ]
