"""
Django settings for datakura project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import json
import sys
from pathlib import Path
from urllib.parse import urlsplit

from decouple import config


def _csv_env(name: str, default: str = "") -> list[str]:
    value = str(config(name, default=default))
    return [item.strip() for item in value.split(",") if item.strip()]


def _normalize_allowed_host(value: str) -> str:
    item = value.strip()
    if not item:
        return ""
    if item == "*":
        return item

    parsed = urlsplit(item if "://" in item else f"//{item}")
    hostname = (parsed.hostname or item).strip().strip(".").lower()
    return hostname


def _normalize_csrf_origin(value: str) -> str:
    item = value.strip()
    if not item:
        return ""
    if "://" in item:
        parsed = urlsplit(item)
        if parsed.scheme and parsed.hostname:
            port = f":{parsed.port}" if parsed.port else ""
            return f"{parsed.scheme}://{parsed.hostname.lower()}{port}"
        return ""
    return f"https://{item.lower()}"


def _allowed_hosts_env(name: str, default: str = "") -> list[str]:
    hosts = [_normalize_allowed_host(item) for item in _csv_env(name, default)]
    return [host for host in hosts if host]


def _csrf_trusted_origins_env(name: str, default: str = "") -> list[str]:
    origins = [_normalize_csrf_origin(item) for item in _csv_env(name, default)]
    return [origin for origin in origins if origin]


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


APPS_DIR = f"{str(BASE_DIR)}/apps"
sys.path.append(APPS_DIR)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = config("SECRET_KEY")

DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS: list[str] = _allowed_hosts_env("ALLOWED_HOSTS", "localhost,127.0.0.1")

CSRF_TRUSTED_ORIGINS: list[str] = _csrf_trusted_origins_env("CSRF_TRUSTED_ORIGINS")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "apps.warehouse",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "ninja.compatibility.files.fix_request_files_middleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# WhiteNoise storage backend (compression + caching)
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

ROOT_URLCONF = "conf.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "conf/templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "conf.context_processors.vite_assets",
            ],
        },
    },
]

WSGI_APPLICATION = "conf.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": config("SQLITE_PATH", default=str(BASE_DIR / "db.sqlite3")),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


JWT_SECRET_KEY = config("JWT_SECRET_KEY")


STATICFILES_DIRS = [
    BASE_DIR / "frontend/dist",
]

# Load Vite manifest
VITE_MANIFEST_PATH = BASE_DIR / "frontend" / "dist" / ".vite" / "manifest.json"


def get_vite_manifest():
    if VITE_MANIFEST_PATH.exists():
        with open(VITE_MANIFEST_PATH, "r") as f:
            return json.load(f)
    else:
        print(f"(!) VITE_MANIFEST_PATH ({VITE_MANIFEST_PATH}) does not exist!")
    return {}


VITE_MANIFEST = get_vite_manifest()
